---
title: "Chlorophyll indicator comparison"
author: "Matt Callahan"
date: "6/15/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidync)
library(tidyverse)
library(lubridate)
library(sf)
library(httr)
library(flextable)
```

## Previous ESP Indicator descriptions
```{r}
#check which indicators were used
data <- httr::content(httr::GET("https://apex.psmfc.org/akfin/data_marts/akmp/esp_indicators?"),
                      type = "application/json"
) %>%
  dplyr::bind_rows()%>%
  filter(grepl('Chlorophylla', INDICATOR_NAME))

#all ours?
unique(data2$CONTACT) #yes

#Descriptions
data%>%group_by(INDICATOR_NAME)%>%
  summarise(unique(PRODUCT_DESCRIPTION))%>%
   flextable()%>%
  theme_box()

```


## MODIS
MODIS data were downloaded from a google folder where Jordan stored them from previous efforts https://drive.google.com/drive/u/1/folders/1mhwQ70mjLrkiQYiQ2oNHx08Q7IlL8Q3-

**Import MODIS data**
```{r}
#EBS
mod_ebs<-readRDS("Data/MODIS/merged_8day_2003_2021_EBS.RDS")
#
```

**Recalculate ESP indices**
```{r}
mod_ebs<-readRDS("Data/MODIS/merged_8day_2003_2021_EBS.RDS")
```